# Generated by Django 4.1.1 on 2022-09-14 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("right_arm_length", models.FloatField(verbose_name="右腕の長さ")),
                ("left_arm_length", models.FloatField(verbose_name="左腕の長さ")),
                ("right_leg_length", models.FloatField(verbose_name="右足の長さ")),
                ("left_leg_length", models.FloatField(verbose_name="左足の長さ")),
                ("right_knee_ankle", models.FloatField(verbose_name="右膝から足首までの長さ")),
                ("left_knee_ankle", models.FloatField(verbose_name="左膝から足首までの長さ")),
                ("back_length", models.FloatField(verbose_name="背中の長さ")),
                ("head_angle", models.FloatField(verbose_name="頭の傾き")),
                ("shoulder_angle", models.FloatField(verbose_name="肩の角度")),
                ("hip_angle", models.FloatField(verbose_name="骨盤の角度")),
                ("neck_angle", models.FloatField(verbose_name="首の角度")),
                ("neck_dent", models.FloatField(verbose_name="首の凹み")),
                ("head_pos", models.FloatField(verbose_name="頭の位置")),
                ("posture", models.CharField(max_length=1, verbose_name="姿勢タイプ")),
                ("image", models.FileField(upload_to="", verbose_name="計測画像")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
