# Generated by Django 4.1.1 on 2022-09-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="計測画像"
            ),
        ),
    ]
