# Generated by Django 4.1.1 on 2022-09-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0002_alter_measure_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="hip_knee",
            field=models.FloatField(default=1, verbose_name="骨盤中央から膝までの長さ"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="knee_ankle",
            field=models.FloatField(default=1, verbose_name="膝から足首までの長さ"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="neck_hip",
            field=models.FloatField(default=1, verbose_name="首から骨盤中央までの長さ"),
            preserve_default=False,
        ),
    ]
