# Generated by Django 4.1.1 on 2022-09-28 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0003_measure_hip_knee_measure_knee_ankle_measure_neck_hip"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="作成日時",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
    ]
