# Generated by Django 4.1.2 on 2022-10-04 17:38

from django.db import migrations, models
import measure.models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0004_measure_created_at_measure_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measure",
            name="image",
        ),
        migrations.AddField(
            model_name="measure",
            name="image1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=measure.models.get_image_path,
                verbose_name="画像",
            ),
        ),
    ]
