# Generated by Django 4.1.2 on 2022-10-04 17:39

from django.db import migrations, models
import measure.models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0005_remove_measure_image_measure_image1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="image1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=measure.models.get_image_path,
                verbose_name="画像2",
            ),
        ),
    ]
