# Generated by Django 4.1.2 on 2022-10-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0007_measure_image2_alter_measure_image1"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measure",
            options={"ordering": ["-created_at"]},
        ),
    ]
