# Generated by Django 4.1.2 on 2022-10-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0008_alter_measure_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measure",
            name="left_knee_ankle",
        ),
        migrations.RemoveField(
            model_name="measure",
            name="neck_angle",
        ),
        migrations.RemoveField(
            model_name="measure",
            name="right_knee_ankle",
        ),
        migrations.AddField(
            model_name="measure",
            name="base_neck",
            field=models.FloatField(default=0, verbose_name="首の付け根"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measure",
            name="head_pos",
            field=models.FloatField(verbose_name="頭（後頭部と付け根の幅）"),
        ),
        migrations.AlterField(
            model_name="measure",
            name="neck_dent",
            field=models.FloatField(verbose_name="首（首の凹みと付け根の幅）"),
        ),
        migrations.AlterField(
            model_name="measure",
            name="posture",
            field=models.CharField(max_length=1, verbose_name="姿勢診断"),
        ),
    ]
