# Generated by Django 4.1.2 on 2022-10-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0009_remove_measure_left_knee_ankle_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measure",
            old_name="head_pos",
            new_name="head_width",
        ),
        migrations.RenameField(
            model_name="measure",
            old_name="base_neck",
            new_name="neck_base",
        ),
        migrations.RenameField(
            model_name="measure",
            old_name="neck_dent",
            new_name="neck_width",
        ),
        migrations.AddField(
            model_name="measure",
            name="back_angle",
            field=models.FloatField(default=1, verbose_name="背中の角度"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="left_shoulder_width",
            field=models.FloatField(default=1, verbose_name="左半身の肩幅"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="right_shoulder_width",
            field=models.FloatField(default=1, verbose_name="右半身の肩幅"),
            preserve_default=False,
        ),
    ]
