# Generated by Django 4.1.3 on 2022-11-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0010_rename_head_pos_measure_head_width_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="left_ear_shoulder",
            field=models.FloatField(default=1, verbose_name="左半身の耳から肩までの長さ"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="right_ear_shoulder",
            field=models.FloatField(default=1, verbose_name="右半身の耳から肩までの長さ"),
            preserve_default=False,
        ),
    ]
