# Generated by Django 4.1.3 on 2022-11-17 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0011_measure_left_ear_shoulder_measure_right_ear_shoulder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measure",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "VP計測結果",
                "verbose_name_plural": "VP計測結果",
            },
        ),
    ]
