# Generated by Django 4.1.4 on 2022-12-14 02:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import measure.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("measure", "0012_alter_measure_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measure",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "VP計測結果（オーダー用）",
                "verbose_name_plural": "VP計測結果（オーダー用）",
            },
        ),
        migrations.CreateModel(
            name="MeasureOnly",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="顧客名")),
                ("kana", models.CharField(max_length=128, verbose_name="フリガナ")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?1?\\d{8,15}$"
                            )
                        ],
                        verbose_name="電話番号",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "post_code",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="郵便番号"
                    ),
                ),
                ("address", models.TextField(blank=True, null=True, verbose_name="住所")),
                (
                    "building",
                    models.TextField(blank=True, null=True, verbose_name="建物名"),
                ),
                ("right_arm_length", models.FloatField(verbose_name="右腕の長さ")),
                ("left_arm_length", models.FloatField(verbose_name="左腕の長さ")),
                ("right_leg_length", models.FloatField(verbose_name="右足の長さ")),
                ("left_leg_length", models.FloatField(verbose_name="左足の長さ")),
                ("knee_ankle", models.FloatField(verbose_name="膝から足首までの長さ")),
                ("back_length", models.FloatField(verbose_name="背中の長さ")),
                ("back_angle", models.FloatField(verbose_name="背中の角度")),
                ("head_angle", models.FloatField(verbose_name="頭の傾き")),
                ("shoulder_angle", models.FloatField(verbose_name="肩の角度")),
                ("hip_angle", models.FloatField(verbose_name="骨盤の角度")),
                ("neck_base", models.FloatField(verbose_name="首の付け根")),
                ("neck_width", models.FloatField(verbose_name="首（首の凹みと付け根の幅）")),
                ("head_width", models.FloatField(verbose_name="頭（後頭部と付け根の幅）")),
                ("posture", models.CharField(max_length=1, verbose_name="姿勢診断")),
                ("neck_hip", models.FloatField(verbose_name="首から骨盤中央までの長さ")),
                ("hip_knee", models.FloatField(verbose_name="骨盤中央から膝までの長さ")),
                ("right_shoulder_width", models.FloatField(verbose_name="右半身の肩幅")),
                ("left_shoulder_width", models.FloatField(verbose_name="左半身の肩幅")),
                ("right_ear_shoulder", models.FloatField(verbose_name="右半身の耳から肩までの長さ")),
                ("left_ear_shoulder", models.FloatField(verbose_name="左半身の耳から肩までの長さ")),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=measure.models.get_image_path,
                        verbose_name="画像1",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=measure.models.get_image_path,
                        verbose_name="画像2",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "VP計測結果（整体師モード）",
                "verbose_name_plural": "VP計測結果（整体師モード）",
                "ordering": ("-created_at",),
            },
        ),
    ]
