# Generated by Django 4.1.4 on 2022-12-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0013_alter_measure_options_measureonly"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measureonly",
            name="kana",
            field=models.CharField(max_length=128, null=True, verbose_name="フリガナ"),
        ),
        migrations.AlterField(
            model_name="measureonly",
            name="name",
            field=models.CharField(max_length=128, null=True, verbose_name="顧客名"),
        ),
    ]
