# Generated by Django 4.1.4 on 2022-12-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0014_alter_measureonly_kana_alter_measureonly_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measureonly",
            name="kana",
            field=models.CharField(max_length=128, null=True, verbose_name="名前（カナ）"),
        ),
        migrations.AlterField(
            model_name="measureonly",
            name="name",
            field=models.CharField(max_length=128, null=True, verbose_name="名前（漢字）"),
        ),
    ]
