# Generated by Django 4.1.1 on 2022-09-14 03:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("measure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatBase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "sex",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="性別",
                    ),
                ),
                ("height_min", models.IntegerField(verbose_name="身長下限")),
                ("height_max", models.IntegerField(verbose_name="身長上限")),
                (
                    "bmi_min",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="BMI下限"
                    ),
                ),
                (
                    "bmi_max",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="BMI上限"
                    ),
                ),
                ("have_backache", models.BooleanField(verbose_name="腰痛")),
                ("have_shoulder_pain", models.BooleanField(verbose_name="肩の痛み")),
                (
                    "hardness",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="硬さ",
                    ),
                ),
                ("posture", models.CharField(max_length=1, verbose_name="姿勢タイプ")),
                ("position1", models.CharField(max_length=10, verbose_name="位置１")),
                ("position2", models.CharField(max_length=10, verbose_name="位置２")),
                ("position3", models.CharField(max_length=10, verbose_name="位置３")),
                ("position4", models.CharField(max_length=10, verbose_name="位置４")),
                ("position5", models.CharField(max_length=10, verbose_name="位置５")),
                ("position6", models.CharField(max_length=10, verbose_name="位置６")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatRec",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("position1", models.CharField(max_length=10, verbose_name="位置１")),
                ("position2", models.CharField(max_length=10, verbose_name="位置２")),
                ("position3", models.CharField(max_length=10, verbose_name="位置３")),
                ("position4", models.CharField(max_length=10, verbose_name="位置４")),
                ("position5", models.CharField(max_length=10, verbose_name="位置５")),
                ("position6", models.CharField(max_length=10, verbose_name="位置６")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PillowRec",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("position1", models.IntegerField(verbose_name="位置１")),
                ("position2", models.IntegerField(verbose_name="位置２")),
                ("position3", models.IntegerField(verbose_name="位置３")),
                ("position4", models.IntegerField(verbose_name="位置４")),
                ("position5", models.IntegerField(verbose_name="位置５")),
                ("position6", models.IntegerField(verbose_name="位置６")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hearing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("sex", models.IntegerField(verbose_name="性別")),
                ("age", models.IntegerField(verbose_name="年齢")),
                ("height", models.FloatField(verbose_name="身長")),
                ("weight", models.FloatField(verbose_name="体重")),
                ("bmi", models.FloatField(verbose_name="BMI")),
                ("question1", models.TextField(verbose_name="質問１")),
                ("answer1", models.CharField(max_length=20, verbose_name="回答１")),
                ("question2", models.TextField(verbose_name="質問２")),
                ("answer2", models.IntegerField(verbose_name="回答２")),
                ("question3", models.TextField(verbose_name="質問３")),
                ("answer3", models.CharField(max_length=20, verbose_name="回答３")),
                ("question4", models.TextField(verbose_name="質問４")),
                ("answer4", models.CharField(max_length=20, verbose_name="回答４")),
                ("question5", models.TextField(verbose_name="質問５")),
                ("answer5", models.CharField(max_length=20, verbose_name="回答５")),
                ("question6", models.TextField(verbose_name="質問６")),
                ("answer6", models.CharField(max_length=20, verbose_name="回答６")),
                ("question7", models.TextField(verbose_name="質問７")),
                ("answer7", models.CharField(max_length=20, verbose_name="回答７")),
                ("question8", models.TextField(verbose_name="質問８")),
                ("answer8", models.CharField(max_length=20, verbose_name="回答８")),
                ("question9", models.TextField(verbose_name="質問９")),
                ("answer9", models.IntegerField(verbose_name="回答９")),
                ("question10", models.TextField(verbose_name="質問１０")),
                ("answer10", models.IntegerField(verbose_name="回答１０")),
                ("question11", models.TextField(verbose_name="質問１１")),
                ("answer11", models.IntegerField(verbose_name="回答１１")),
                ("question12", models.TextField(verbose_name="質問１２")),
                (
                    "answer12",
                    models.CharField(max_length=20, null=True, verbose_name="回答１２"),
                ),
                ("question13", models.TextField(verbose_name="質問１３")),
                ("answer13", models.IntegerField(verbose_name="回答１３")),
                ("question14", models.TextField(verbose_name="質問１４")),
                (
                    "answer14",
                    models.CharField(max_length=20, null=True, verbose_name="回答１４"),
                ),
                ("question15", models.TextField(verbose_name="質問１５")),
                ("answer15", models.IntegerField(verbose_name="回答１５")),
                ("question16", models.TextField(verbose_name="質問１６")),
                (
                    "answer16",
                    models.CharField(max_length=20, null=True, verbose_name="回答１６"),
                ),
                ("question17", models.TextField(verbose_name="質問１７")),
                ("answer17", models.IntegerField(verbose_name="回答１７")),
                ("question18", models.TextField(verbose_name="質問１８")),
                ("answer18", models.CharField(max_length=20, verbose_name="回答１８")),
                ("question19", models.TextField(verbose_name="質問１９")),
                ("answer19", models.CharField(max_length=20, verbose_name="回答１９")),
                ("question20", models.TextField(verbose_name="質問２０")),
                ("answer20", models.CharField(max_length=20, verbose_name="回答２０")),
                ("question21", models.TextField(verbose_name="質問２１")),
                ("answer21", models.CharField(max_length=20, verbose_name="回答２１")),
                ("question22", models.TextField(verbose_name="質問２２")),
                ("answer22", models.CharField(max_length=20, verbose_name="回答２２")),
                ("question23", models.TextField(verbose_name="質問２３")),
                ("answer23", models.CharField(max_length=20, verbose_name="回答２３")),
                ("question24", models.TextField(verbose_name="質問２４")),
                ("answer24", models.CharField(max_length=20, verbose_name="回答２４")),
                ("question25", models.TextField(verbose_name="質問２５")),
                ("answer25", models.CharField(max_length=20, verbose_name="回答２５")),
                ("question26", models.TextField(verbose_name="質問２６")),
                ("answer26", models.CharField(max_length=20, verbose_name="回答２６")),
                ("question27", models.TextField(verbose_name="質問２７")),
                ("answer27", models.CharField(max_length=20, verbose_name="回答２７")),
                ("question28", models.TextField(verbose_name="質問２８")),
                ("answer28", models.CharField(max_length=20, verbose_name="回答２８")),
                ("question29", models.TextField(verbose_name="質問２９")),
                ("answer29", models.CharField(max_length=20, verbose_name="回答２９")),
                ("question30", models.TextField(verbose_name="質問３０")),
                ("answer30", models.CharField(max_length=20, verbose_name="回答３０")),
                ("question31", models.TextField(verbose_name="質問３１")),
                ("answer31", models.CharField(max_length=200, verbose_name="回答３１")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "mat_rec",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommends.matrec",
                    ),
                ),
                (
                    "pillow_rec",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommends.pillowrec",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vp_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="measure.measure",
                    ),
                ),
            ],
        ),
    ]
