# Generated by Django 4.1.1 on 2022-09-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommends", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="matbase",
            index=models.Index(
                fields=[
                    "bmi_min",
                    "bmi_max",
                    "height_min",
                    "height_max",
                    "hardness",
                    "posture",
                    "have_shoulder_pain",
                    "have_backache",
                    "sex",
                ],
                name="recommends__bmi_min_0f2e5d_idx",
            ),
        ),
    ]
