# Generated by Django 4.1.1 on 2022-09-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommends", "0002_matbase_recommends__bmi_min_0f2e5d_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="matbase",
            name="recommends__bmi_min_0f2e5d_idx",
        ),
        migrations.AddIndex(
            model_name="matbase",
            index=models.Index(
                fields=[
                    "sex",
                    "have_backache",
                    "have_shoulder_pain",
                    "posture",
                    "hardness",
                    "bmi_min",
                    "bmi_max",
                    "height_min",
                    "height_max",
                ],
                name="recommends__sex_c8529c_idx",
            ),
        ),
    ]
