# Generated by Django 4.1.1 on 2022-09-22 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommends", "0003_remove_matbase_recommends__bmi_min_0f2e5d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matrec",
            name="support_pad1_n1",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="サポートパッド1の番号",
            ),
        ),
        migrations.AddField(
            model_name="matrec",
            name="support_pad1_p1",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="サポートパッド1の位置",
            ),
        ),
        migrations.AddField(
            model_name="matrec",
            name="support_pad2_n1",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="サポートパッド2の番号",
            ),
        ),
        migrations.AddField(
            model_name="matrec",
            name="support_pad2_p1",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="サポートパッド2の位置",
            ),
        ),
        migrations.AddField(
            model_name="matrec",
            name="support_pad3_n1",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="サポートパッド3の番号",
            ),
        ),
        migrations.AddField(
            model_name="matrec",
            name="support_pad3_p1",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="サポートパッド3の位置",
            ),
        ),
        migrations.AddField(
            model_name="matrec",
            name="support_pad4_n1",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="サポートパッド4の番号",
            ),
        ),
        migrations.AddField(
            model_name="matrec",
            name="support_pad4_p1",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="サポートパッド4の位置",
            ),
        ),
    ]
