# Generated by Django 4.1.1 on 2022-09-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommends", "0004_matrec_support_pad1_n1_matrec_support_pad1_p1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matrec",
            old_name="support_pad1_n1",
            new_name="support_pad1_n",
        ),
        migrations.RenameField(
            model_name="matrec",
            old_name="support_pad1_p1",
            new_name="support_pad1_p",
        ),
        migrations.RenameField(
            model_name="matrec",
            old_name="support_pad2_n1",
            new_name="support_pad2_n",
        ),
        migrations.RenameField(
            model_name="matrec",
            old_name="support_pad2_p1",
            new_name="support_pad2_p",
        ),
        migrations.RenameField(
            model_name="matrec",
            old_name="support_pad3_n1",
            new_name="support_pad3_n",
        ),
        migrations.RenameField(
            model_name="matrec",
            old_name="support_pad3_p1",
            new_name="support_pad3_p",
        ),
        migrations.RenameField(
            model_name="matrec",
            old_name="support_pad4_n1",
            new_name="support_pad4_n",
        ),
        migrations.RenameField(
            model_name="matrec",
            old_name="support_pad4_p1",
            new_name="support_pad4_p",
        ),
    ]
