# Generated by Django 4.1.2 on 2022-10-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommends", "0005_rename_support_pad1_n1_matrec_support_pad1_n_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hearing",
            name="answer26",
            field=models.CharField(max_length=20, null=True, verbose_name="回答２６"),
        ),
        migrations.AlterField(
            model_name="hearing",
            name="answer27",
            field=models.CharField(max_length=20, null=True, verbose_name="回答２７"),
        ),
    ]
