# Generated by Django 4.1.2 on 2022-10-25 08:21

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("recommends", "0006_alter_hearing_answer26_alter_hearing_answer27"),
    ]

    operations = [
        migrations.CreateModel(
            name="PillowBase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("material", models.CharField(max_length=15, verbose_name="枕素材")),
                ("position1", models.IntegerField(verbose_name="位置１")),
                ("position2", models.IntegerField(verbose_name="位置２")),
                ("position3", models.IntegerField(verbose_name="位置３")),
                ("position4", models.IntegerField(verbose_name="位置４")),
                ("position5", models.IntegerField(verbose_name="位置５")),
                ("position6", models.IntegerField(verbose_name="位置６")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="hearing",
            name="answer31",
        ),
        migrations.RemoveField(
            model_name="hearing",
            name="question31",
        ),
        migrations.AddField(
            model_name="hearing",
            name="both",
            field=models.BooleanField(default=False, verbose_name="枕とマットレス同時購入"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pillowrec",
            name="diff_position1",
            field=models.IntegerField(default=1, verbose_name="差分位置１"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pillowrec",
            name="diff_position2",
            field=models.IntegerField(default=1, verbose_name="差分位置２"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pillowrec",
            name="diff_position3",
            field=models.IntegerField(default=1, verbose_name="差分位置３"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pillowrec",
            name="diff_position4",
            field=models.IntegerField(default=1, verbose_name="差分位置４"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pillowrec",
            name="diff_position5",
            field=models.IntegerField(default=1, verbose_name="差分位置５"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pillowrec",
            name="diff_position6",
            field=models.IntegerField(default=1, verbose_name="差分位置６"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pillowrec",
            name="sheet",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="シートの厚み",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hearing",
            name="answer27",
            field=models.CharField(default=1, max_length=20, verbose_name="回答２７"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hearing",
            name="answer30",
            field=models.CharField(max_length=200, null=True, verbose_name="回答３０"),
        ),
    ]
