# Generated by Django 4.1.2 on 2022-11-08 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommends", "0007_pillowbase_remove_hearing_answer31_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pillowrec",
            name="sheet",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="シートの厚み",
            ),
        ),
    ]
