# Generated by Django 4.1.3 on 2022-11-17 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommends", "0008_alter_pillowrec_sheet"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hearing",
            options={"verbose_name": "ヒアリング", "verbose_name_plural": "ヒアリング"},
        ),
        migrations.AlterModelOptions(
            name="matbase",
            options={
                "verbose_name": "マットレスモックデータ",
                "verbose_name_plural": "マットレスモックデータ",
            },
        ),
        migrations.AlterModelOptions(
            name="matrec",
            options={"verbose_name": "おすすめマットレス", "verbose_name_plural": "おすすめマットレス"},
        ),
        migrations.AlterModelOptions(
            name="pillowbase",
            options={"verbose_name": "枕モックデータ", "verbose_name_plural": "枕モックデータ"},
        ),
        migrations.AlterModelOptions(
            name="pillowrec",
            options={"verbose_name": "おすすめ枕", "verbose_name_plural": "おすすめ枕"},
        ),
    ]
