# Generated by Django 4.1.4 on 2022-12-14 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommends", "0009_alter_hearing_options_alter_matbase_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matbase",
            options={
                "verbose_name": "マットレスベースデータ",
                "verbose_name_plural": "マットレスベースデータ",
            },
        ),
        migrations.AlterModelOptions(
            name="pillowbase",
            options={"verbose_name": "枕ベースデータ", "verbose_name_plural": "枕ベースデータ"},
        ),
    ]
