# Generated by Django 4.1.2 on 2022-10-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "ユーザー",
                "verbose_name_plural": "ユーザー",
            },
        ),
    ]
