# Generated by Django 4.1.2 on 2022-10-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_crowd_funding_user",
            field=models.BooleanField(default=False, verbose_name="クラウドファンディングユーザー権限"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_furusato_tax_user",
            field=models.BooleanField(default=False, verbose_name="ふるさと納税ユーザ権限"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_salon_user",
            field=models.BooleanField(default=False, verbose_name="サロンユーザ権限"),
        ),
    ]
