# Generated by Django 4.1.1 on 2022-09-27 13:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recommends", "0003_remove_matbase_recommends__bmi_min_0f2e5d_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="顧客名")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?1?\\d{8,15}$"
                            )
                        ],
                        verbose_name="電話番号",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="メールアドレス")),
                ("post_code", models.IntegerField(verbose_name="郵便番号")),
                ("address", models.TextField(verbose_name="住所")),
                ("building", models.TextField(verbose_name="建物名")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("size", models.CharField(max_length=10, verbose_name="サイズ")),
                ("thickness", models.IntegerField(verbose_name="厚み")),
                (
                    "cover_material",
                    models.CharField(max_length=10, null=True, verbose_name="カバー素材"),
                ),
                (
                    "cover_color",
                    models.CharField(max_length=10, null=True, verbose_name="カバー色"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "mat_rec1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mat_rec1",
                        to="recommends.matrec",
                    ),
                ),
                (
                    "mat_rec2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mat_rec2",
                        to="recommends.matrec",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PillowOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("size", models.CharField(max_length=10, verbose_name="サイズ")),
                ("material", models.CharField(max_length=10, verbose_name="枕素材")),
                (
                    "cover_material",
                    models.CharField(max_length=10, null=True, verbose_name="カバー素材"),
                ),
                (
                    "cover_color1",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="カバー色１",
                    ),
                ),
                (
                    "cover_color2",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="カバー色２",
                    ),
                ),
                (
                    "cover_color3",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="カバー色３",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "pillow_rec",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommends.pillowrec",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to="orders.customer",
                    ),
                ),
                (
                    "mat_order",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.matorder",
                    ),
                ),
                (
                    "pillow_order1",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pillow_order1",
                        to="orders.pilloworder",
                    ),
                ),
                (
                    "pillow_order2",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pillow_order2",
                        to="orders.pilloworder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
