# Generated by Django 4.1.1 on 2022-09-27 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recommends", "0003_remove_matbase_recommends__bmi_min_0f2e5d_idx_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="post_code",
            field=models.CharField(max_length=8, verbose_name="郵便番号"),
        ),
        migrations.AlterField(
            model_name="pilloworder",
            name="pillow_rec",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recommends.pillowrec"
            ),
        ),
    ]
