# Generated by Django 4.1.2 on 2022-10-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_customer_post_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "注文顧客情報",
                "verbose_name_plural": "注文顧客情報",
            },
        ),
        migrations.AlterModelOptions(
            name="matorder",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "マットレスオーダー情報",
                "verbose_name_plural": "マットレスオーダー情報",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "オーダー総合情報",
                "verbose_name_plural": "オーダー総合情報",
            },
        ),
        migrations.AlterModelOptions(
            name="pilloworder",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "枕オーダー情報",
                "verbose_name_plural": "枕オーダー情報",
            },
        ),
    ]
