# Generated by Django 4.1.2 on 2022-10-10 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0003_alter_customer_options_alter_matorder_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="orders.customer",
                verbose_name="注文者",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="注文ID",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="mat_order",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.matorder",
                verbose_name="マットレスオーダー",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pillow_order1",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pillow_order1",
                to="orders.pilloworder",
                verbose_name="枕オーダー1",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pillow_order2",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pillow_order2",
                to="orders.pilloworder",
                verbose_name="枕オーダー2",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザー",
            ),
        ),
    ]
