# Generated by Django 4.1.2 on 2022-10-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recommends", "0005_rename_support_pad1_n1_matrec_support_pad1_n_and_more"),
        ("orders", "0004_alter_order_customer_alter_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matorder",
            name="mat_rec1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mat_rec1",
                to="recommends.matrec",
                verbose_name="マットレスレコメンド1",
            ),
        ),
        migrations.AlterField(
            model_name="matorder",
            name="mat_rec2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mat_rec2",
                to="recommends.matrec",
                verbose_name="マットレスレコメンド2",
            ),
        ),
        migrations.AlterField(
            model_name="pilloworder",
            name="pillow_rec",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recommends.pillowrec",
                verbose_name="枕レコメンド",
            ),
        ),
    ]
