# Generated by Django 4.1.2 on 2022-10-16 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recommends", "0005_rename_support_pad1_n1_matrec_support_pad1_n_and_more"),
        ("orders", "0005_alter_matorder_mat_rec1_alter_matorder_mat_rec2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="hearing1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hearing1",
                to="recommends.hearing",
                verbose_name="ヒアリング1人目",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="hearing2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hearing2",
                to="recommends.hearing",
                verbose_name="ヒアリング2人目",
            ),
        ),
    ]
