# Generated by Django 4.1.2 on 2022-10-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_hearing1_order_hearing2"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="memo",
            field=models.TextField(null=True, verbose_name="ねむりやメモ"),
        ),
    ]
