# Generated by Django 4.1.2 on 2022-10-16 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_hearing1_alter_order_hearing2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="mat_order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.matorder",
                verbose_name="マットレスオーダー",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pillow_order1",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pillow_order1",
                to="orders.pilloworder",
                verbose_name="枕オーダー1",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pillow_order2",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pillow_order2",
                to="orders.pilloworder",
                verbose_name="枕オーダー2",
            ),
        ),
    ]
