# Generated by Django 4.1.2 on 2022-11-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_order_mat_order_alter_order_pillow_order1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="block_number",
            field=models.TextField(default=1, verbose_name="丁目・番地"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="kana",
            field=models.CharField(default=1, max_length=128, verbose_name="フリガナ"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="building",
            field=models.TextField(blank=True, null=True, verbose_name="建物名"),
        ),
    ]
