# Generated by Django 4.1.2 on 2022-11-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_customer_block_number_customer_kana_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="building",
            field=models.TextField(null=True, verbose_name="建物名"),
        ),
    ]
