# Generated by Django 4.1.3 on 2022-11-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_customer_building"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pilloworder",
            name="size",
        ),
    ]
