# Generated by Django 4.1.3 on 2022-11-17 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_remove_pilloworder_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matorder",
            name="cover_color",
        ),
        migrations.AddField(
            model_name="matorder",
            name="cover_color1",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="カバー色１",
            ),
        ),
        migrations.AddField(
            model_name="matorder",
            name="cover_color2",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="カバー色２",
            ),
        ),
        migrations.AddField(
            model_name="matorder",
            name="cover_color3",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="カバー色３",
            ),
        ),
    ]
