# Generated by Django 4.1.4 on 2022-12-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_remove_matorder_cover_color_matorder_cover_color1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="block_number",
        ),
    ]
